server:
  port: 10000
spring:
  application:
    name: account_platform
  datasource:
    username: gonnaup
    password: 123456
    url: jdbc:mysql://gonnaup.org/accountplatform?useSSL=false
    hikari:
      maximum-pool-size: 8
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      repositories:
        enabled: false
      host: gonnaup.org
      password: 123456
  cache:
    type: REDIS
    redis:
      time-to-live: 30m
accountplatform:
  account:
    default:
      account-name:
        prefix: xid_
        length: 30
      avatar:
        host: http://localhost
        path: /static/
        default-file-name: default_avatar.svg

